import type { Metadata } from "next";
import "./globals.css";
import "./manrope.css";
import "./nagel.css";
import "./material-icons.css";
import "./material-symbols.css";
import { cn } from "@/lib/utils";
import AppProvider from "./_providers/app-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontManrope = {
  subsets: ["latin"],
  variable: "font-manrope",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontManrope.variable,
        )}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
